
notify:
  ding:
    secret: "SEC15f73ce79811aaef654daa07e16b126794ed98ee4971f18662afea53debe41cf"
    url: "https://oapi.dingtalk.com/robot/send?access_token=41f519fcb601d6f084155c6f35bbba4d2290d7db19fa7a0f5d2404f06fae6bc9"
    send-wait-milliseconds: 1666
cbg:
  queryUrl: "https://stzb.cbg.163.com/cgi/api/query?platform_type=1"
  queryDetailUrl: "https://stzb.cbg.163.com/cgi/api/get_equip_detail"
  webDetailUrl: "https://stzb.cbg.163.com/cgi/mweb/equip"
  gamerResUrl: "https://cbg-stzb.res.netease.com"
  query-config:
    id: 1
    minPrice: 400000
    maxPrice: 1500000
    hero: 100016,100015,100030,100027,100035,100526
    skill: 200900,200834,200767,200647,200724,200754,200755,200757,200204,200198,200207,200687,200816,200228,200235,200194,200201
    option-hero: 100631,100013,100615,100479,100072,100019,100020,100618,100021,100023,100496,100451,100475,100574,100582,100480,100534,100494,100630,100029,100028,100478,100101,100476,100024,100586,100337,100031,100589,102001
    option-skill: 200220,200673,200721,200684,200801,200829,200800,200847,200784,200817,200233,200658,200659,200674,200676,200844,200715,200717,200818,200734,200731,200826,200119,200122,200130,200863,200813,200208,200853,200217,200839,200862,200224,200226,200786,200184,200714,200239,200644,200926,200646,200883,200888,200814,200815,200788,200789,200812,200688,200781,200782,200783,200691,200822,200823,200632
    # 可选 英雄 和 技能 的最低契合度
    option-hero-min-fit-degree: 70
    option-skill-min-fit-degree: 70
  return:
    paging: "paging"
    status: "status"
    msg: "msg"
    num: "total_num"
    result: "result"
    icon: "icon"
    is-last-page: "is_last_page"
    # 以下为进一步查询藏宝阁角色详细信息后获得
    detail-gamer-key: "equip"
    detail-gamer-info-key: "equip_desc"
    gamer-name-key: "equip_name"
    sell-status-key: "status"
    sell-status-name-key: "status_desc"
    first-price-key: "first_onsale_price"
    # 以下为详情中多出来的具体有什么卡 技能等信息, 再详细信息返回后的 equip.equip_desc的JSON字符串中
    detail-card-key: "card"
    detail-card-id-key: "hero_id"
    detail-card-feature-key: "card_feature"
    detail-skill-key: "skill"
    detail-skill-id-key: "skill_id"
    detail-dian-cang-key: "card_dian_cang"
    detail-dian-ji-key: "card_dian_ji"
    detail-tenure-key: "tenure"
    detail-tenure-yuan-bao-key: "yuan_bao"
  gamer:
    key:
      sn: "game_ordersn"
      price: "price"
      highLight: "highlights"
      serverId: "serverid"
      otherInfo: "other_info"
      oi:
        basicAttr: "basic_attrs"
        dianJi: "available_dian_ji_count"
        dianCang: "available_dian_cang_count"
  schedule:
    find-delay: 30000
    notice-delay: 5000
    clear-delay: 60000
  game-auto-config-key:
    hero: "hero"
    skills: "skill"
    dian-ji: "dian_ji"
    dian-cang: "dian_cang"
    special-hero: "special_hero"
    hero-key:
      country: "country"
      icon-hero-id: "icon_hero_id"
      pinyin: "pinyin"
      name: "name"
      season: "season"
      hero-type: "hero_type"
      hero-id: "hero_id"
      quality: "quality"
    skill-key:
      name: "name"
      skill-id: "skill_id"
      skill-type: "skill_type"


