spring:
  data:
    mongodb:
#      uri: "mongodb://192.168.31.221:27017/stzb"
      host: "114.215.141.118"
#      host: "45.43.37.164"
      port: 27017
      database: "stzb"
      username: "app"
      password: "app123123"
      authentication-database: "stzb"



